server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    # 是否向自己注册
    registerWithEureka: false
    fetchRegistry: false
    # 服务注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0